language: c
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - yasm
      - diffutils
      - gcc-5
      - gcc-6
      - clang-3.6
matrix:
  include:
    - os: linux
      compiler: gcc
      env: COMPILER=gcc-5
    - os: linux
      compiler: gcc
      env: COMPILER=gcc-6
    - os: linux
      compiler: clang
      env: COMPILER=clang-3.6
    - os: osx
      compiler: clang
      env: COMPILER=clang
cache:
  directories:
    - libav-samples
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update --all; fi
install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install yasm; fi
script:
  - mkdir -p libav-samples
  - ./configure --samples=libav-samples --cc=$COMPILER
  - make -j 8
  - make fate-rsync
  - make check -j 8
